metric: COCO
num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: data/datasets/lego_labeling_samples/COCODataFmt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: data/datasets/coco/lego_labeling_samples/COCODataFmt
